# =====================
# Base Configuration
# =====================
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}  # Default to prod for Railway
  application:
    name: sales-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sales_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  security:
    user:
      name: root
      password:
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: simple
    cache-names: products,users,orders,customers

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.salesapp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log
    max-size: 10MB
    max-history: 30

jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-for-production-change-this}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

app:
  name: ${APP_NAME:Sales Application}
  version: ${APP_VERSION:1.0.0}
  environment: ${APP_ENVIRONMENT:production}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost:3000, hades-clothing.up.railway.app, https://hades-clothing-fe.vercel.app/}
  file:
    upload:
      max-size: 10MB
      allowed-types: image/jpeg,image/png,image/gif,application/pdf
  notification:
    email:
      enabled: true
    sms:
      enabled: false
  inventory:
    low-stock-threshold: 10
    auto-reorder: false

# ---
# Dev, prod, and local profiles remain unchanged below

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/sales_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cache:
    type: simple
    cache-names: products,users,orders,customers

logging:
  level:
    com.salesapp: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cache:
    type: simple
    cache-names: products,users,orders,customers


logging:
  level:
    com.salesapp: INFO
    org.springframework.security: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

jwt:
  secret: ${JWT_SECRET}

---

#spring:
#  config:
#    activate:
#      on-profile: local
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#  cache:
#    type: simple
#    cache-names: products,users,orders,customers
